// Mock template data - Add this to your component or separate file

export const mockTemplates = [
  {
    _id: "template-1",
    title: "Modern Portfolio Template",
    author: "Sarah Chen",
    category: "Portfolio",
    views: "12.5K",
    likes: "2.3K",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&h=600&fit=crop",
    data: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          version: "5.3.0",
          originX: "left",
          originY: "top",
          left: 0,
          top: 0,
          width: 800,
          height: 600,
          fill: "#6366f1",
          stroke: null,
          strokeWidth: 1,
          opacity: 1,
          angle: 0,
          selectable: false,
        },
        {
          type: "text",
          version: "5.3.0",
          originX: "left",
          originY: "top",
          left: 100,
          top: 250,
          width: 400,
          height: 80,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          opacity: 1,
          angle: 0,
          text: "Portfolio",
          fontSize: 72,
          fontWeight: "bold",
          fontFamily: "Arial",
          textAlign: "left",
        },
      ],
      background: "#6366f1",
    },
  },
  {
    _id: "template-2",
    title: "SaaS Landing Page Pro",
    author: "Alex Rivera",
    category: "Landing Page",
    views: "18.2K",
    likes: "3.8K",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?w=800&h=600&fit=crop",
    data: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          version: "5.3.0",
          originX: "left",
          originY: "top",
          left: 0,
          top: 0,
          width: 800,
          height: 600,
          fill: "#991b1b",
          stroke: null,
          strokeWidth: 1,
          opacity: 1,
          angle: 0,
          selectable: false,
        },
        {
          type: "text",
          version: "5.3.0",
          originX: "left",
          originY: "top",
          left: 100,
          top: 250,
          width: 350,
          height: 75,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          opacity: 1,
          angle: 0,
          text: "SaaS Pro",
          fontSize: 64,
          fontWeight: "bold",
          fontFamily: "Arial",
          textAlign: "left",
        },
      ],
      background: "#991b1b",
    },
  },
  {
    _id: "template-3",
    title: "E-commerce Product Grid",
    author: "Maya Patel",
    category: "E-commerce",
    views: "9.7K",
    likes: "1.9K",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1618005198920-f0cb6201c115?w=800&h=600&fit=crop",
    data: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          version: "5.3.0",
          originX: "left",
          originY: "top",
          left: 0,
          top: 0,
          width: 800,
          height: 600,
          fill: "#f59e0b",
          stroke: null,
          strokeWidth: 1,
          opacity: 1,
          angle: 0,
          selectable: false,
        },
        {
          type: "text",
          version: "5.3.0",
          originX: "left",
          originY: "top",
          left: 100,
          top: 250,
          width: 400,
          height: 78,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          opacity: 1,
          angle: 0,
          text: "Ecommerce",
          fontSize: 68,
          fontWeight: "bold",
          fontFamily: "Arial",
          textAlign: "left",
        },
      ],
      background: "#f59e0b",
    },
  },
  {
    _id: "template-4",
    title: "Mobile App Showcase",
    author: "James Wilson",
    category: "Mobile",
    views: "15.4K",
    likes: "2.8K",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&h=600&fit=crop",
    data: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          version: "5.3.0",
          originX: "left",
          originY: "top",
          left: 0,
          top: 0,
          width: 800,
          height: 600,
          fill: "#10b981",
          stroke: null,
          strokeWidth: 1,
          opacity: 1,
          angle: 0,
          selectable: false,
        },
        {
          type: "text",
          version: "5.3.0",
          originX: "left",
          originY: "top",
          left: 100,
          top: 250,
          width: 380,
          height: 72,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          opacity: 1,
          angle: 0,
          text: "Mobile App",
          fontSize: 62,
          fontWeight: "bold",
          fontFamily: "Arial",
          textAlign: "left",
        },
      ],
      background: "#10b981",
    },
  },
  {
    _id: "template-5",
    title: "Minimalist Brand Identity",
    author: "Emma Thompson",
    category: "Branding",
    views: "11.3K",
    likes: "2.5K",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?w=800&h=600&fit=crop",
    data: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          version: "5.3.0",
          originX: "left",
          originY: "top",
          left: 0,
          top: 0,
          width: 800,
          height: 600,
          fill: "#3b82f6",
          stroke: null,
          strokeWidth: 1,
          opacity: 1,
          angle: 0,
          selectable: false,
        },
        {
          type: "text",
          version: "5.3.0",
          originX: "left",
          originY: "top",
          left: 100,
          top: 250,
          width: 350,
          height: 80,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          opacity: 1,
          angle: 0,
          text: "Branding",
          fontSize: 70,
          fontWeight: "bold",
          fontFamily: "Arial",
          textAlign: "left",
        },
      ],
      background: "#3b82f6",
    },
  },
  {
    _id: "template-6",
    title: "Dashboard Analytics UI",
    author: "David Kim",
    category: "Dashboard",
    views: "14.8K",
    likes: "3.2K",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1618005198920-f0cb6201c115?w=800&h=600&fit=crop",
    data: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          version: "5.3.0",
          originX: "left",
          originY: "top",
          left: 0,
          top: 0,
          width: 800,
          height: 600,
          fill: "#ef4444",
          stroke: null,
          strokeWidth: 1,
          opacity: 1,
          angle: 0,
          selectable: false,
        },
        {
          type: "text",
          version: "5.3.0",
          originX: "left",
          originY: "top",
          left: 100,
          top: 250,
          width: 350,
          height: 76,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          opacity: 1,
          angle: 0,
          text: "Analytics",
          fontSize: 66,
          fontWeight: "bold",
          fontFamily: "Arial",
          textAlign: "left",
        },
      ],
      background: "#ef4444",
    },
  },
];
