export const mockTemplates = [
  {
    _id: "template-1",
    title: "Modern Portfolio Template",
    author: "Sarah Chen",
    category: "Portfolio",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&h=300&fit=crop",
    data: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          left: 480,
          top: 0,
          width: 320,
          height: 600,
          fill: "#f3f4f6",
          selectable: false,
          name: "Background Panel",
        },
        {
          type: "circle",
          left: 530,
          top: 80,
          radius: 90,
          fill: "#e5e7eb",
          stroke: "#ffffff",
          strokeWidth: 8,
          name: "Image Placeholder",
        },
        {
          type: "i-text",
          left: 80,
          top: 150,
          fill: "#111827",
          text: "Jane Doe",
          fontSize: 80,
          fontWeight: "bold",
          fontFamily: "Helvetica",
          name: "Main Heading",
        },
        {
          type: "line",
          left: 80,
          top: 255,
          x1: 0,
          y1: 0,
          x2: 120,
          y2: 0,
          stroke: "#4f46e5",
          strokeWidth: 4,
        },
        {
          type: "i-text",
          left: 80,
          top: 280,
          fill: "#374151",
          text: "CREATIVE DIRECTOR & PHOTOGRAPHER",
          fontSize: 18,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          charSpacing: 150,
          name: "Subheading",
        },
        {
          type: "i-text",
          left: 80,
          top: 340,
          width: 350,
          fill: "#6b7285",
          text: "A passionate designer focused on creating modern and impactful digital experiences that users love.",
          fontSize: 16,
          lineHeight: 1.5,
          fontFamily: "Helvetica",
          name: "Description",
        },
        {
          type: "rect",
          left: 80,
          top: 450,
          width: 180,
          height: 50,
          fill: "#4f46e5",
          rx: 8,
          ry: 8,
          name: "Button Background",
        },
        {
          type: "i-text",
          left: 118,
          top: 464,
          fill: "#ffffff",
          text: "View Work",
          fontSize: 18,
          fontWeight: "600",
          fontFamily: "Helvetica",
          name: "Button Text",
          selectable: false,
        },
      ],
      background: "#ffffff",
    },
  },
  {
    _id: "template-2",
    title: "SaaS Landing Page Pro",
    author: "Alex Rivera",
    category: "Landing Page",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop",
    data: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          left: 450,
          top: 100,
          width: 280,
          height: 400,
          fill: "#f9fafb",
          stroke: "#e5e7eb",
          strokeWidth: 2,
          rx: 12,
          ry: 12,
          name: "Image Placeholder",
        },
        {
          type: "i-text",
          left: 80,
          top: 180,
          width: 350,
          fill: "#111827",
          text: "Supercharge Your Workflow",
          fontSize: 52,
          fontWeight: "bold",
          fontFamily: "Arial",
          lineHeight: 1.2,
        },
        {
          type: "i-text",
          left: 80,
          top: 320,
          width: 320,
          fill: "#4b5563",
          text: "The ultimate platform to help you and your team get things done faster than ever before.",
          fontSize: 18,
          fontFamily: "Arial",
          lineHeight: 1.6,
        },
        {
          type: "rect",
          left: 80,
          top: 420,
          width: 200,
          height: 50,
          fill: "#be123c",
          rx: 8,
          ry: 8,
        },
        {
          type: "i-text",
          left: 115,
          top: 434,
          fill: "#ffffff",
          text: "Get Started Free",
          fontSize: 18,
          fontWeight: "600",
          fontFamily: "Arial",
        },
      ],
      background: "#ffffff",
    },
  },
  {
    _id: "template-3",
    title: "E-commerce Product Grid",
    author: "Maya Patel",
    category: "E-commerce",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=300&fit=crop",
    data: {
      version: "5.3.0",
      objects: [
        {
          type: "i-text",
          left: 80,
          top: 60,
          fill: "#111827",
          text: "New Arrivals",
          fontSize: 48,
          fontWeight: "bold",
          fontFamily: "Georgia",
        },
        {
          type: "rect",
          left: 80,
          top: 150,
          width: 200,
          height: 200,
          fill: "#e5e7eb",
        },
        {
          type: "i-text",
          left: 80,
          top: 360,
          text: "Classic Timepiece",
          fontSize: 18,
          fontFamily: "Georgia",
        },
        {
          type: "i-text",
          left: 80,
          top: 385,
          text: "$199.99",
          fontSize: 16,
          fontWeight: "bold",
          fill: "#d97706",
          fontFamily: "Georgia",
        },
        {
          type: "rect",
          left: 300,
          top: 150,
          width: 200,
          height: 200,
          fill: "#e5e7eb",
        },
        {
          type: "i-text",
          left: 300,
          top: 360,
          text: "Leather Backpack",
          fontSize: 18,
          fontFamily: "Georgia",
        },
        {
          type: "i-text",
          left: 300,
          top: 385,
          text: "$124.50",
          fontSize: 16,
          fontWeight: "bold",
          fill: "#d97706",
          fontFamily: "Georgia",
        },
        {
          type: "rect",
          left: 520,
          top: 150,
          width: 200,
          height: 200,
          fill: "#e5e7eb",
        },
        {
          type: "i-text",
          left: 520,
          top: 360,
          text: "Designer Sunglasses",
          fontSize: 18,
          fontFamily: "Georgia",
        },
        {
          type: "i-text",
          left: 520,
          top: 385,
          text: "$85.00",
          fontSize: 16,
          fontWeight: "bold",
          fill: "#d97706",
          fontFamily: "Georgia",
        },
      ],
      background: "#fffbeb",
    },
  },
  {
    _id: "template-4",
    title: "Mobile App Showcase",
    author: "James Wilson",
    category: "Mobile",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=400&h=300&fit=crop",
    data: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          left: 480,
          top: 80,
          width: 240,
          height: 480,
          fill: "#1f2937",
          stroke: "#4b5563",
          strokeWidth: 10,
          rx: 30,
          ry: 30,
        },
        {
          type: "rect",
          left: 495,
          top: 95,
          width: 210,
          height: 450,
          fill: "#10b981",
        },
        {
          type: "i-text",
          left: 80,
          top: 180,
          width: 350,
          fill: "#111827",
          text: "The Future of Mobile.",
          fontSize: 52,
          fontWeight: "bold",
          fontFamily: "Verdana",
          lineHeight: 1.2,
        },
        {
          type: "i-text",
          left: 80,
          top: 300,
          width: 320,
          fill: "#4b5563",
          text: "Experience an intuitive and beautiful interface designed to make your life easier.",
          fontSize: 18,
          fontFamily: "Verdana",
          lineHeight: 1.6,
        },
      ],
      background: "#ffffff",
    },
  },
  {
    _id: "template-5",
    title: "Minimalist Brand Identity",
    author: "Emma Thompson",
    category: "Branding",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1518655048521-f130df041f66?w=400&h=300&fit=crop",
    data: {
      version: "5.3.0",
      objects: [
        {
          type: "i-text",
          left: 80,
          top: 250,
          text: "AURA",
          fontFamily: "Arial",
          fontSize: 120,
          fontWeight: "900",
          charSpacing: 200,
          fill: "#1f2937",
        },
        {
          type: "line",
          left: 80,
          top: 380,
          x1: 0,
          y1: 0,
          x2: 385,
          y2: 0,
          stroke: "#3b82f6",
          strokeWidth: 3,
        },
        {
          type: "i-text",
          left: 80,
          top: 400,
          text: "STUDIO",
          fontFamily: "Arial",
          fontSize: 24,
          fontWeight: "normal",
          charSpacing: 800,
          fill: "#6b7285",
        },
      ],
      background: "#ffffff",
    },
  },
  {
    _id: "template-6",
    title: "Dashboard Analytics UI",
    author: "David Kim",
    category: "Dashboard",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop",
    data: {
      version: "5.3.0",
      objects: [
        {
          type: "i-text",
          left: 50,
          top: 50,
          text: "Performance Overview",
          fontSize: 32,
          fontWeight: "bold",
          fontFamily: "Helvetica",
        },
        {
          type: "rect",
          left: 50,
          top: 120,
          width: 220,
          height: 120,
          fill: "#ffffff",
          stroke: "#e5e7eb",
          rx: 8,
          ry: 8,
        },
        {
          type: "i-text",
          left: 70,
          top: 140,
          text: "Total Revenue",
          fontSize: 16,
          fill: "#6b7285",
        },
        {
          type: "i-text",
          left: 70,
          top: 170,
          text: "$45,231",
          fontSize: 36,
          fontWeight: "600",
          fill: "#111827",
        },
        {
          type: "rect",
          left: 290,
          top: 120,
          width: 220,
          height: 120,
          fill: "#ffffff",
          stroke: "#e5e7eb",
          rx: 8,
          ry: 8,
        },
        {
          type: "i-text",
          left: 310,
          top: 140,
          text: "Subscriptions",
          fontSize: 16,
          fill: "#6b7285",
        },
        {
          type: "i-text",
          left: 310,
          top: 170,
          text: "+2,350",
          fontSize: 36,
          fontWeight: "600",
          fill: "#111827",
        },
        {
          type: "rect",
          left: 530,
          top: 120,
          width: 220,
          height: 120,
          fill: "#ffffff",
          stroke: "#e5e7eb",
          rx: 8,
          ry: 8,
        },
        {
          type: "i-text",
          left: 550,
          top: 140,
          text: "Conversion Rate",
          fontSize: 16,
          fill: "#6b7285",
        },
        {
          type: "i-text",
          left: 550,
          top: 170,
          text: "12.3%",
          fontSize: 36,
          fontWeight: "600",
          fill: "#111827",
        },
        {
          type: "rect",
          left: 50,
          top: 280,
          width: 700,
          height: 280,
          fill: "#ffffff",
          stroke: "#e5e7eb",
          rx: 8,
          ry: 8,
        },
        {
          type: "i-text",
          left: 70,
          top: 300,
          text: "Weekly Sales",
          fontSize: 18,
          fontWeight: "600",
        },
        {
          type: "rect",
          left: 100,
          top: 400,
          width: 50,
          height: 140,
          fill: "#dcfce7",
        },
        {
          type: "rect",
          left: 200,
          top: 350,
          width: 50,
          height: 190,
          fill: "#dcfce7",
        },
        {
          type: "rect",
          left: 300,
          top: 450,
          width: 50,
          height: 90,
          fill: "#fee2e2",
        },
        {
          type: "rect",
          left: 400,
          top: 380,
          width: 50,
          height: 160,
          fill: "#dcfce7",
        },
      ],
      background: "#f9fafb",
    },
  },
];
